name: Continuous integration

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "**.rs"
      - "**.suql"
  pull_request:
  merge_group:

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - name: Install toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Checkout Sources
        uses: actions/checkout@v3

      - name: Setup cache
        uses: Swatinem/rust-cache@v2

      - name: Run check
        uses: actions-rs/cargo@v1
        with:
          command: check

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - name: Install toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          override: true
          components: clippy
          profile: minimal

      - name: Checkout Sources
        uses: actions/checkout@v3

      - name: Setup cache
        uses: Swatinem/rust-cache@v2

      - name: Run clippy
        run: cargo clippy -- -D warnings

  test:
    needs: [clippy, check]
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: Install toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          profile: minimal

      - name: Checkout Sources
        uses: actions/checkout@v3

      - name: Setup cache
        uses: Swatinem/rust-cache@v2

      - name: Tests
        env:
          SURREALDB_ENDPOINT: localhost:8080
          SURREALDB_USERNAME: root
          SURREALDB_PASSWORD: root
        run: |
          docker run -d -p 8080:8000 surrealdb/surrealdb:1.0.0-beta.9-20230402 start -u root -p root
          cargo test
