name: Continuous integration

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "**.rs"
      - "**.suql"
  pull_request:
  merge_group:

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - name: Install toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Checkout Sources
        uses: actions/checkout@v4

      - name: Setup cache
        uses: Swatinem/rust-cache@v2

      - name: Run check
        uses: actions-rs/cargo@v1
        with:
          command: check

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - name: Install toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          override: true
          components: clippy
          profile: minimal

      - name: Checkout Sources
        uses: actions/checkout@v4

      - name: Setup cache
        uses: Swatinem/rust-cache@v2

      - name: Run clippy
        run: make clippy 

  test:
    needs: [clippy, check]
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: Install toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          profile: minimal

      - name: Checkout Sources
        uses: actions/checkout@v4

      - name: Setup cache
        uses: Swatinem/rust-cache@v2

      - name: Tests
        run: make test 
