name: Release

on:
  push:
    tags:
      - "v*.*.*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/randoooom/eventplanner

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-04-21
          override: true

      - name: Checkout Sources
        uses: actions/checkout@v3

      - name: Setup cache
        uses: Swatinem/rust-cache@v2

      - name: Run check
        uses: actions-rs/cargo@v1
        with:
          command: check

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-04-21
          override: true
          components: clippy
          profile: minimal

      - name: Checkout Sources
        uses: actions/checkout@v3

      - name: Setup cache
        uses: Swatinem/rust-cache@v2

      - name: Run clippy
        run: cargo clippy -- -D warnings

  test:
    needs: [clippy, check]
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-04-21
          override: true
          profile: minimal

      - name: Checkout Sources
        uses: actions/checkout@v3

      - name: Setup cache
        uses: Swatinem/rust-cache@v2

      - name: Tests
        env:
          SURREALDB_ENDPOINT: localhost:8080
          SURREALDB_USERNAME: root
          SURREALDB_PASSWORD: root
        run: |
          docker run -d -p 8080:8000 surrealdb/surrealdb:latest start -u root -p root
          cargo test

  docker-ssr:
    needs: [ test ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login into repository
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure tag
        shell: bash
        run: |
          VERSION=${{ github.ref_name }}
          echo "VERSION=${VERSION:1}" | tr + - >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest,${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          target: ssr

  docker-static:
    needs: [ test ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login into repository
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure tag
        shell: bash
        run: |
          VERSION=${{ github.ref_name }}
          echo "VERSION=${VERSION:1}" | tr + - >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:static,${{ env.IMAGE_NAME }}:static-${{ env.VERSION }}
          target: static
